"""Questions table added

Revision ID: d46bd9155840
Revises: 56191aea0036
Create Date: 2020-03-24 16:25:45.477508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46bd9155840'
down_revision = '56191aea0036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_timestamp'), 'questions', ['timestamp'], unique=False)
    op.add_column('question', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'user', ['userid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'userid')
    op.drop_index(op.f('ix_questions_timestamp'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
